"""Generate reports/business_insights.md from the processed CSV outputs.

Every number in the report is read from data/processed/, so the text can never
drift from the analysis. The data is SYNTHETIC; the report says so explicitly.
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / "data" / "processed"


def fmt(x: float) -> str:
    return f"{x:,.2f}"


def main() -> None:
    kpi = pd.read_csv(P / "financial_kpis.csv").iloc[0]
    seg = pd.read_csv(P / "segment_summary.csv")
    cust = pd.read_csv(P / "customer_kpis.csv").iloc[0]
    cur = pd.read_csv(P / "currency_summary.csv")
    monthly = pd.read_csv(P / "monthly_financial_summary.csv")
    anomalies = pd.read_csv(P / "anomaly_rule_summary.csv")
    quality = pd.read_csv(P / "quality_report.csv")
    n_tx = int(cur["transaction_count"].sum())
    n_customers = int(cust["customers_in_data"])

    top = seg[seg["segment"].isin(["Loyal", "High Value"])]
    top_n, top_cust_pct, top_val_pct = int(top["customers"].sum()), top["customer_share_pct"].sum(), top["value_share_pct"].sum()
    largest = seg.loc[seg["customers"].idxmax()]
    low = seg[seg["segment"] == "Low Activity"].iloc[0]
    any_rule = anomalies[anomalies["rule"] == "any_rule"].iloc[0]
    complete = monthly[~monthly["is_partial_month"]]
    neg_months = int((complete["net_flow"] < 0).sum())
    partial = monthly[monthly["is_partial_month"]]["month"].tolist()
    all_pass = bool((quality["status"] == "pass").all())

    cur_rows = "\n".join(
        f"| {r.currency} | {int(r.transaction_count):,} | {fmt(r.total_native_amount)} | {fmt(r.total_amount_usd)} |"
        for r in cur.itertuples()
    )
    seg_rows = "\n".join(
        f"| {r.segment} | {int(r.customers)} | {r.customer_share_pct:.1f}% | {r.value_share_pct:.1f}% |" for r in seg.itertuples()
    )
    quality_rows = "\n".join(f"- `{r.check}`: **{r.status}** ({r.detail})" for r in quality.itertuples())

    text = f"""# Business Insights

> **SYNTHETIC DATA - demo results only.** The figures below come from a fully synthetic dataset ({n_customers} customers, {n_tx:,} transactions) generated by a public generator. They must NOT be presented as real-bank performance or used for real business decisions. See `data/raw/SOURCE.md`.

> **Currency note.** The source mixes USD, GBP and EUR. All value KPIs are expressed in a **USD-equivalent** using *illustrative fixed rates* (`data/reference/fx_rates.csv`), not market data. Native-currency totals are shown below and must not be added together.

## Executive summary

- The dataset contains **{n_customers} customers**; {int(cust['active_customers'])} have at least one transaction. A 100% activity rate is a property of the generated sample, not a retention benchmark.
- Transaction value excluding internal-transfer legs: **{fmt(kpi['total_transaction_value'])} USD-eq.**, average **{fmt(kpi['average_transaction_value'])}**.
- Deposits **{fmt(kpi['total_deposits'])}**, withdrawals **{fmt(kpi['total_withdrawals'])}**, fees **{fmt(kpi['total_fees'])}** -> net flow **{fmt(kpi['net_transaction_flow'])}** (deposits minus withdrawals and fees).
- Internal transfers ({int(kpi['internal_transfer_legs']):,} legs, {fmt(kpi['internal_transfer_volume'])} across both legs) net to zero and are reported separately.
- Data-quality checks: {'all passed' if all_pass else 'some checks need review (see below)'}.

## Native currency vs USD-equivalent

| Currency | Transactions | Total (native units) | Total (USD-eq.) |
|---|---:|---:|---:|
{cur_rows}

## Customer insights (RFM segments)

| Segment | Customers | Customer share | Value share |
|---|---:|---:|---:|
{seg_rows}

| Finding | Evidence | Business implication | Suggested action |
|---|---:|---|---|
| Loyal + High Value are a minority with outsized value | {top_n} customers ({top_cust_pct:.1f}%) contribute {top_val_pct:.1f}% of value | Retention risk is concentrated in a smaller group | Prioritize service quality and retention monitoring for these segments |
| {largest['segment']} is the largest segment | {int(largest['customers'])} customers ({largest['customer_share_pct']:.1f}%) contribute {largest['value_share_pct']:.1f}% of value | A sizeable base could be developed into higher-value segments | Test engagement/bundling experiments and measure conversion |
| Low Activity contributes little | {int(low['customers'])} customers ({low['customer_share_pct']:.1f}%) contribute {low['value_share_pct']:.1f}% of value | Broad interventions may not be cost-effective | Test low-cost reactivation campaigns |

## Transaction and financial insights

- Complete months analysed: {len(complete)}. Net flow was negative in **{neg_months}** of them, so aggregate flow should be monitored together with month-level volatility.
- The final month ({', '.join(partial) if partial else 'none'}) is {'partial and is excluded from trend charts and growth rates' if partial else 'complete'}.
- Fees are reported separately from withdrawals; internal transfers are excluded from total transaction value because each transfer appears as two offsetting legs.
- Transaction type mapping was normalized during adaptation; the original type is preserved in `source_transaction_type`.

## Anomaly observations

The screening flagged **{int(any_rule['flagged_rows']):,} of {n_tx:,} rows ({any_rule['share_pct']:.2f}%)**. Rules: robust z-score of log(amount) within each customer x category (recurring subscriptions, salary and transfers excluded) plus customer-day frequency far above the customer's own typical day. This is a *screening population*, not a fraud rate; review samples in context before any operational decision.

## Data quality

{quality_rows}

## Method and limitations

- **Synthetic data**: no behavioural conclusion transfers to a real bank.
- **FX**: fixed illustrative rates; with real data use dated market rates per transaction.
- `transaction_status` was set to `Completed` because the source has no status field (an assumption, not a source fact).
- `branches.csv` and `products.csv` are derived compatibility tables, not source master data.
- RFM thresholds are quintile-based for this demo and should be recalculated on real data.
- Statistical anomaly flags do not prove fraud.

## KPI definitions

| KPI | Definition used | Filters / notes |
|---|---|---|
| Total transaction value | Sum of `amount_usd` excluding internal-transfer legs | USD-equivalent, illustrative FX |
| Average transaction value | Mean `amount_usd` excluding internal-transfer legs | Same filter |
| Total deposits / withdrawals | Sum of `amount_usd` by normalized type; fees excluded from withdrawals | |
| Net transaction flow | Deposits - withdrawals - fees | Internal transfers net to zero |
| Active customers | Customers with at least one included transaction | Full generated period |
| High-value customer | RFM segment Loyal / High Value | Quintile-based demo threshold |
"""
    (ROOT / "reports" / "business_insights.md").write_text(text, encoding="utf-8")
    print("Report generated from processed outputs.")


if __name__ == "__main__":
    main()
